export const genre = [
    { title: "All", category: "All" },
    { title: "Action", category: "Action" },
    { title: "Adventure", category: "Adventure" },
    { title: "Comedy", category: "Comedy" },
    { title: "Crime ", category: "Crime" },
    { title: "Mystery", category: "Mystery" },
    { title: "Fantasy", category: "Fantasy" },
    { title: "Historical", category: "Historical" },
    { title: "Horror", category: "Horror" },
    { title: "Satire", category: "Satire" },
    { title: "SciFi", category: "SciFi" },
    { title: "Thriller", category: "Thriller" },
    { title: "Animation", category: "Animation" },
    { title: "Drama", category: "Drama" },
];

export const year = [
    { title: "All", category: "All" },
    { title: "1975", category: "1975" },
    { title: "1976", category: "1976" },
    { title: "1977", category: "1977" },
    { title: "1978", category: "1978" },
    { title: "1979", category: "1979" },
    { title: "1980", category: "1980" },
    { title: "1981", category: "1981" },
    { title: "1982", category: "1982" },
    { title: "1983", category: "1983" },
    { title: "1984", category: "1984" },
    { title: "1985", category: "1985" },
    { title: "1986", category: "1986" },
    { title: "1987", category: "1987" },
    { title: "1988", category: "1988" },
    { title: "1989", category: "1989" },
    { title: "1990", category: "1990" },
    { title: "1991", category: "1991" },
    { title: "1992", category: "1992" },
    { title: "1993", category: "1993" },
    { title: "1994", category: "1994" },
    { title: "1995", category: "1995" },
    { title: "1996", category: "1996" },
    { title: "1997", category: "1997" },
    { title: "1998", category: "1998" },
    { title: "1999", category: "1999" },
    { title: "2000", category: "2000" },
    { title: "2001", category: "2001" },
    { title: "2002", category: "2002" },
    { title: "2003", category: "2003" },
    { title: "2004", category: "2004" },
    { title: "2005", category: "2005" },
    { title: "2006", category: "2006" },
    { title: "2007", category: "2007" },
    { title: "2008", category: "2008" },
    { title: "2009", category: "2009" },
    { title: "2010", category: "2010" },
    { title: "2011", category: "2011" },
    { title: "2012", category: "2012" },
    { title: "2013", category: "2013" },
    { title: "2014", category: "2014" },
    { title: "2015", category: "2015" },
    { title: "2016", category: "2016" },
    { title: "2017", category: "2017" },
    { title: "2018", category: "2018" },
    { title: "2019", category: "2019" },
    { title: "2020", category: "2020" },
    { title: "2021", category: "2021" },
    { title: "2022", category: "2022" },
    { title: "2023", category: "2023" },
    { title: "2024", category: "2024" }
];

export const awards = [
    { title: "All", category: "All" },
    { title: "Best Picture", category: "Best Picture" },
    { title: "2nd Best Picture", category: "2nd Best Picture" },
    { title: "3rd Best Picture", category: "3rd Best Picture" },
    { title: "4th Best Picture", category: "4th Best Picture" },
    { title: "Best Director", category: "Best Director" },
    { title: "Best Screenplay", category: "Best Screenplay" },
    { title: "Best Cinematography", category: "Best Cinematography" },
    { title: "Best Editing", category: "Best Editing" },
    { title: "Best Production Design", category: "Best Production Design" },
    { title: "Best Visual Effects", category: "Best Visual Effects" },
    { title: "Best Sound", category: "Best Sound" },
    { title: "Best Musical Score", category: "Best Musical Score" },
    { title: "Best Original Theme Song", category: "Best Original Theme Song" },
    { title: "Best Float Award", category: "Best Float Award" },
    { title: "Gat Puno Antonio Villegas Cultural Award", category: "Cultural Award" },
    { title: "FPJ Memorial Award", category: "FPJ Memorial Award" },
    { title: "Gender Sensitivity Award", category: "Gender Sensitivity Award" },
    { title: "Lifetime Achievement Award", category: "Lifetime Achievement Award" },
    { title: "Special Jury Prize", category: "Special Jury Prize" },
    { title: "Special Jury Citation", category: "Special Jury Citation" },
    { title: "Manay Ichu Vera Perez Memorial Award", category: "Memorial Award" }
];

